### ISSUE TITLE
Vertex color support in THREE.OBJLoader2

### ISSUE THREAD

**Issue by kaisalmen** [Sean-Bradley/objVertexColors#1]
Hi, I have a preview of `THREE.OBJLoader2` with vertex color support available (see last post):
https://github.com/mrdoob/three.js/issues/11422

I used your model emmy3d as reference to check the implementation and I hope you are ok with that. `OBJLoader` and `OBJLoader2` (new in three.js r85) will both support this in the future.

This is of course not an issue. I just wanted to let you know.... ;-)

**Comment by Sean-Bradley** [comment]
No problem at all,

**Comment by Sean-Bradley** [comment]
closing issue
